from config.settings import WINDOW_WIDTH, WINDOW_HEIGHT, CELL_SIZE, BORDER_SIZE, FIELD_SIZE, WIDTH_IN_CELLS, \
    HEIGHT_IN_CELLS, ANCHOR
from config.colors import WATER, AIR, SHIP, RED_DOT, RED_ERROR, END_TEXT, CLOSE_BUTTON, START_BUTTON
